<?php

namespace ContactsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function findAllContactsSortByName()
    {
        return $this->getEntityManager()->createQuery(
            "SELECT c FROM ContactsBundle:Contact c ORDER BY c.name ASC"
        )
            ->getResult();

    }   
}
