<?php

namespace ContactsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneRepository extends EntityRepository
{
    public function showAllByContact($id)
    {
        return $this->getEntityManager()->createQuery(
            "SELECT a FROM ContactsBundle:Phone a JOIN ContactsBundle:Contact b WHERE a.contact = :id"
        )->setParameter('id', $id)
            ->getResult();
    }
}
